version: '3.9'

services:
  fastapi:
    container_name: QueueAPI
    build: .
    command: uvicorn --factory api.app:create_app --reload --host 0.0.0.0 --port 8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: Queue_DB
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: queue
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data